version: '2'

services:
  postgres:
    container_name: nest-api-doctor
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest-api
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
